version: 1.0.{build}
image: Visual Studio 2017
before_build:
  pwsh: msbuild Itn.DotNet.NewClassGenerator.sln /t:Restore
after_build:
  pwsh: msbuild Itn.DotNet.NewClassGenerator.sln /t:Pack /p:Configuration=Release
build:
  verbosity: minimal
  publish_core_console: true
artifacts:
  - path: '**\*.nupkg'
    name: NuGetPackages
deploy:
  - provider: NuGet
    api_key:
      secure: bY30MmrEC8g9+KkstQtTTJPjUYWuOZrBNObPuUo8Qj6iBJ1Coi7kYb1fnUzPhCsU
    on:
      APPVEYOR_REPO_TAG: true
    artifact: NuGetPackages
  - provider: GitHub
    auth_token:
      secure: VO7JazH8iheMwssIPuXQE7uEOqaoHvdpvqfgBg9pDcVhx2qosCGlxeurzjSm4rOr
    artifact: NuGetPackages
    draft: false
    prerelease: false
    on:
      branch: master
      appveyor_repo_tag: true
