version: 1.0.{build}
image: Visual Studio 2017
build:
  verbosity: minimal
deploy:
  - provider: NuGet
    api_key:
      secure: bY30MmrEC8g9+KkstQtTTJPjUYWuOZrBNObPuUo8Qj6iBJ1Coi7kYb1fnUzPhCsU
    on:
      APPVEYOR_REPO_TAG: true